### ISSUE TITLE
Add a license please?

### ISSUE THREAD

**Issue by traverseda** [farialima/django-tasks#5]
This looks like a good fit for a project I'm involved in, where celery doesn't quite work. Could you please release this under an actual license so that I can try to get it working on modern django?

**Comment by farialima** [comment]
Hi Traverseda -

I'd love it if you use it, however let me warn you: this code has not been maintained for quite a long time... not sure it works with recent versions of Django

Now regarding the license, you can see in each file that there's a license statement - BSD 3 clauses

**Comment by traverseda** [comment]
I've actually got it running fine under django 4.0, it only required me to change ~4 lines of code!

**Comment by farialima** [comment]
yes I just saw, congratulations ! 

and in fact it was already licensed in BSD 3-clause license, in each source file... I had forgotten :)

**Comment by traverseda** [comment]
I noticed that a bit later, that works for me!

Thanks
